apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: image-is-signed-by-github-actions
spec:
  images:
  # All images in example repository matched
  - glob: "**"
  authorities:
  - keyless:
      # Signed by the public Fulcio certificate authority
      url: https://fulcio.sigstore.dev
      identities:
      # Matches the Github Actions OIDC issuer
      - issuer: https://token.actions.githubusercontent.com
        # Matches a specific github workflow on main branch
        subject: "https://github.com/michaelvl/sigstore-in-toto-workshop/.github/workflows/container-build.yml@refs/heads/main"
    ctlog:
      url: https://rekor.sigstore.dev
