name: App build and push

on:
  push:
    branches:
      - main
    paths:
      - main.go
      - go.mod
      - Dockerfile
      - .github/workflows/build-and-push.yaml

permissions:
  contents: read
  packages: write

jobs:
  # First, we run project specific local tests
  # FIXME: This has been temporarily removed to speed up development
  # app-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

  #     - name: Set up Go
  #       uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # tag=v5.0.0
  #       with:
  #         go-version-file: "go.mod"
  #         cache: true

  #     - name: Lint
  #       run: |
  #         make build lint container

  # Second, we hand over the build to the trusted builder
  app-build:
  #  needs:
  #  - app-test
    uses: michaelvl/gha-reusable-workflows/.github/workflows/container-build-push.yaml@main
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: read

  app-scan:
    needs:
    - app-build
    uses: michaelvl/gha-reusable-workflows/.github/workflows/container-scan.yaml@main
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      digest: ${{ needs.app-build.outputs.digest }}

  app-policy-check:
    needs:
    - app-build
    - app-scan # For cosign race
    uses: michaelvl/gha-reusable-workflows/.github/workflows/policy-verification.yaml@main
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      digest: ${{ needs.app-build.outputs.digest }}
