name: App build and push

on:
  push:
    branches:
      - main
    paths:
      - main.go
      - go.mod
      - Dockerfile
      - .github/workflows/**

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: michaelvl/gha-reusable-workflows/.github/workflows/container-build-push.yaml@main

