name: Chart build and push

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - .github/workflows/chart-build-and-push.yaml

permissions:
  contents: read
  packages: write

jobs:
  # First, we run project specific local tests
  # FIXME: This has been temporarily removed to speed up development
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Chart test
        run: |
          make test-chart

  # Second, we hand over the build to the trusted builder
  chart-build:
    needs:
    - chart-test
    uses: michaelvl/gha-reusable-workflows/.github/workflows/chart-build-push.yaml@main
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: read
    with:
      chartDir: charts
      chartName: sigstore-in-toto-workshop-helm
