name: App build and push

on:
  push:
    branches:
      - main

permissions:
  contents: read   # Testing, expected to be 'write'
  id-token: write

jobs:
  app-source-attest:
    uses: michaelvl/gha-reusable-workflows/.github/workflows/source-attester.yaml@main
