name: App source attester

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  app-source-attest:
    uses: michaelvl/gha-reusable-workflows/.github/workflows/source-attester.yaml@main
